import { Inter } from "next/font/google"; // Ganti dengan font Anda (misal: GeistSans)
import "./globals.css";

// Asumsi Anda mengimpor font seperti ini
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Tambahkan kelas utility Tailwind langsung di sini.
        Pastikan variabel font Anda juga disertakan.
      */}
      <body
        className={`${inter.variable} antialiased bg-gray-900 text-white`}
      >
        {children}
      </body>
    </html>
  );
}